services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: camagru_web
    ports:
      - "8081:80"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - WEB_PORT=8081
    depends_on:
      - db
    networks:
      - camagru_network

  db:
    image: mariadb:10.11
    container_name: camagru_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - camagru_db_data:/var/lib/mysql
    networks:
      - camagru_network

volumes:
  camagru_db_data:
    driver: local

networks:
  camagru_network:
    driver: bridge
